[project]
name = "modal-comfyui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.47.2",
    "modal>=1.1.4",
]

[tool.flake8]
max-line-length = 100